module.exports = {
  main_screen: {
    marginTop: 30,
    display: "flex",
    flexDirection: "column",
    backgroundColor: "white",
    alignItems: "center",
    width: "100%",
    height: "100%",
  },
  main_screen_display: {
    elevation: 10,
    width: "95%",
    backgroundColor: "#dfdfdfff",
    borderRadius: 10,
    display: "flex",
    marginBottom: 10,
    padding: 10,
  },
  main_screen_display_text: {
    fontSize: 50,
    textAlign: "right",
  },
  main_screen_keypad: {
    width: "100%",
    height: "75%",
    display: "flex",
  },
  main_screen_keypad_row: {
    width: "100%",
    height: "20%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "white",
    padding: 10,
  },
  btn_outer: {
    width: 70,
    height: 70,
    borderRadius: 100,
    backgroundColor: "#e0e0e0",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  btn1_outer: {
    width: 70,
    height: 70,
    borderRadius: 100,
    backgroundColor: "red",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  bg_button: {
    fontSize: 30,
    color: "black",
  },
  bg1_button: {
    fontSize: 30,
    color: "white",
  },
  bg2_button: {
    fontSize: 30,
    color: "black",
    backgroundColor: "#f5a623",
    width: 70,
    height: 70,
    borderRadius: 100,
    backgroundColor: "#f5a623",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
};
